[build.env]
passthrough = [
    "SCCACHE_ERROR_LOG",
    "SCCACHE_LOG",
    "SCCACHE_AZURE_CONNECTION_STRING",
    "SCCACHE_AZURE_BLOB_CONTAINER",
    "SCCACHE_DIR",
    "MAJOR_VERSION",
    "SRC_PATH",
    "DEST_PATH",
    "RUST_BACKTRACE",
    "LIBCEC_VENDORED",
    "LIBCEC_NO_VENDOR",
    "LIBCEC_STATIC",
]
[build]
default-target = "armv7-unknown-linux-gnueabihf"
pre-build = [
    "apt-get install libudev-dev"
]
